ktor {
  deployment {
    port = 8081
  }
  application {
    modules = [ com.albertiacob91.movieversekmp.server.ApplicationKt.module ]
  }
}

tmdb {
  apiKey = "local-dev"
  baseUrl = "https://api.themoviedb.org/3"
}