ktor {
  deployment {
    port = 8081
  }
  application {
    modules = [ com.albertiacob91.movieversekmp.server.ApplicationKt.module ]
  }
}

tmdb {
  apiKey = "a05372d814f4f5333d3706d6e471e9a5"
  baseUrl = "https://api.themoviedb.org/3"
}